import { Category, Book, Author, EventSession } from './types';

export const categories: Category[] = [
  {
    id: 'fiction',
    name: 'Fiction',
    tagline: 'Where imagination knows no boundaries.',
    gradient: 'linear-gradient(135deg, #4f46e5 0%, #312e81 100%)',
    textCol: 'text-indigo-200',
    bgDecorative: 'bg-indigo-500/10 border-indigo-500/20',
    icon: 'Star',
    image: 'https://images.unsplash.com/photo-1474932431283-43c1626f6323?q=80&w=600&auto=format&fit=crop',
  },
  {
    id: 'non-fiction',
    name: 'Non-Fiction',
    tagline: 'Unearthing raw truths and human wisdom.',
    gradient: 'linear-gradient(135deg, #0f172a 0%, #334155 100%)',
    textCol: 'text-slate-300',
    bgDecorative: 'bg-slate-500/10 border-slate-500/20',
    icon: 'Compass',
    image: 'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?q=80&w=600&auto=format&fit=crop',
  },
  {
    id: 'educational',
    name: 'Educational',
    tagline: 'Unlock key formulas and shape future minds.',
    gradient: 'linear-gradient(135deg, #0891b2 0%, #164e63 100%)',
    textCol: 'text-cyan-200',
    bgDecorative: 'bg-cyan-500/10 border-cyan-500/20',
    icon: 'GraduationCap',
    image: 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?q=80&w=600&auto=format&fit=crop',
  },
  {
    id: 'comics',
    name: 'Comics',
    tagline: 'Stunning sequential art in cosmic visual panels.',
    gradient: 'linear-gradient(135deg, #db2777 0%, #4d0727 100%)',
    textCol: 'text-pink-200',
    bgDecorative: 'bg-pink-500/10 border-pink-500/20',
    icon: 'Tv',
    image: 'https://images.unsplash.com/photo-1560942485-b2a11cc13456?q=80&w=600&auto=format&fit=crop',
  },
  {
    id: 'novels',
    name: 'Novels',
    tagline: 'Character-driven epics detailing the human journey.',
    gradient: 'linear-gradient(135deg, #dc2626 0%, #5c0606 100%)',
    textCol: 'text-red-200',
    bgDecorative: 'bg-red-500/10 border-red-500/20',
    icon: 'Bookmark',
    image: 'https://images.unsplash.com/photo-1543002588-bfa74002ed7e?q=80&w=600&auto=format&fit=crop',
  },
  {
    id: 'poetry',
    name: 'Poetry',
    tagline: 'The rhythm of syllables painting silent landscapes.',
    gradient: 'linear-gradient(135deg, #10b981 0%, #064e3b 100%)',
    textCol: 'text-emerald-200',
    bgDecorative: 'bg-emerald-500/10 border-emerald-500/20',
    icon: 'Feather',
    image: 'https://images.unsplash.com/photo-1518156677180-95a2893f3e9f?q=80&w=600&auto=format&fit=crop',
  },
  {
    id: 'self-help',
    name: 'Self-Help',
    tagline: 'Ignite inner fires and master personal routines.',
    gradient: 'linear-gradient(135deg, #ea580c 0%, #4c1d05 100%)',
    textCol: 'text-orange-200',
    bgDecorative: 'bg-orange-500/10 border-orange-500/20',
    icon: 'Zap',
    image: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?q=80&w=600&auto=format&fit=crop',
  },
  {
    id: 'cpp-programming',
    name: 'C++ Systems',
    tagline: 'High-performance compilation in deep Titian Red & C++ Royal Violet.',
    gradient: 'linear-gradient(135deg, #d32f2f 0%, #3e1b7a 100%)', // Titian Red (#d32f2f) and C++ Royal Violet (#3e1b7a)
    textCol: 'text-rose-200',
    bgDecorative: 'bg-rose-500/10 border-rose-500/20',
    icon: 'Cpu',
    image: 'https://images.unsplash.com/photo-1629654297299-c8506221ca97?q=80&w=600&auto=format&fit=crop',
  },
];

export const books: Book[] = [
  // Fiction
  {
    id: 'fic-1',
    title: 'The Starlight Epoch',
    author: 'Elena Rostova',
    genre: 'Cosmic Fiction',
    categoryId: 'fiction',
    shortDesc: 'A sweeping saga of forgotten stars, rogue celestial pilots, and a cosmic library containing the universe\'s first whispers.',
    longDesc: 'In the cold expanse of Sector 9, the Starlight Epoch approaches—a time when ancient star systems collapse to give birth to pure knowledge. Elena Rostova crafts a spellbinding narrative of celestial pilots who navigate physical orbits to locate a mythical space-bound library. As the stars fade, their stories are carved directly into light-sensitive manuscripts.',
    pages: 412,
    rating: 4.9,
    year: '2026',
    coverGradient: 'linear-gradient(135deg, #312e81 0%, #1e1b4b 100%)',
    published: 'Starlight Press',
    coverImage: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=80&w=600&auto=format&fit=crop',
  },
  {
    id: 'fic-2',
    title: 'Echoes of the Void',
    author: 'Zael Vance',
    genre: 'Sci-Fi / Fantasy',
    categoryId: 'fiction',
    shortDesc: 'In a city built on the interior rings of an ancient dormant star, young cartographers map spatial anomalies.',
    longDesc: 'When the gravitational waves of the Outer Sphere begin to distort time, Aurelia discovers that she is the only person who can hear warning bells before each seismic shift. Zael Vance crafts a highly philosophical adventure exploring parallel dimensions, the memory of stones, and a fragile society floating on the precipice of absolute silence.',
    pages: 360,
    rating: 4.8,
    year: '2025',
    coverGradient: 'linear-gradient(135deg, #4f46e5 0%, #3730a3 100%)',
    published: 'Voyager Books',
    coverImage: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?q=80&w=600&auto=format&fit=crop',
  },
  // Non-Fiction
  {
    id: 'nf-1',
    title: 'Architectures of Quiet',
    author: 'Dr. Arthur Sterling',
    genre: 'Design / Philosophy',
    categoryId: 'non-fiction',
    shortDesc: 'An exploration of brutalist design, Japanese tea rooms, and the deliberate creation of silence in noisy cities.',
    longDesc: 'How do our physical surroundings govern our psychological state? Dr. Sterling investigates architectural histories spanning over six centuries to reveal how spatial volume, shadow-play, and negative space serve as non-verbal therapies. A vital study for designers, dreamers, and anyone seeking clarity in an era of industrial noise.',
    pages: 288,
    rating: 4.7,
    year: '2026',
    coverGradient: 'linear-gradient(135deg, #1e293b 0%, #0f172a 100%)',
    published: 'Aesthetic Press',
    coverImage: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=600&auto=format&fit=crop',
  },
  {
    id: 'nf-2',
    title: 'Our Electric Canvas',
    author: 'Mira K. Thorne',
    genre: 'Technology & Humanity',
    categoryId: 'non-fiction',
    shortDesc: 'Tracing the profound connection between neural interfaces, computer graphics, and the future of creative expression.',
    longDesc: 'Mira K. Thorne tracks fifty years of computing breakthroughs to deliver a masterful analysis of human agency. By interviewing leading developers, neurologists, and abstract artists, she establishes that binary processors are not replacing craftsmanship, but rather expanding the human sensory canvas to infinity.',
    pages: 342,
    rating: 4.9,
    year: '2026',
    coverGradient: 'linear-gradient(135deg, #334155 0%, #1e293b 100%)',
    published: 'Circuit Publishing',
    coverImage: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?q=80&w=600&auto=format&fit=crop',
  },
  // Educational
  {
    id: 'edu-1',
    title: 'Design Systems in Motion',
    author: 'Professor Lucas Crane',
    genre: 'Web UI / Computer Science',
    categoryId: 'educational',
    shortDesc: 'A practical, visually rich masterclass on creating micro-interactions and math-driven UI components.',
    longDesc: 'Professor Lucas Crane compiles two decades of interface engineering research into an essential textbook. From cubic-bezier curves to spring physics web simulations, this guide teaches front-end developers to treat layouts not as static pages, but as living, physical environments that react with kinetic choreography.',
    pages: 495,
    rating: 5.0,
    year: '2026',
    coverGradient: 'linear-gradient(135deg, #0e7490 0%, #115e59 100%)',
    published: 'TechCraft Academy',
    coverImage: 'https://images.unsplash.com/photo-1502239608882-93b729c6af43?q=80&w=600&auto=format&fit=crop',
  },
  // Comics
  {
    id: 'com-1',
    title: 'Neon Odyssey: Year Zero',
    author: 'Takeshi Kenji',
    genre: 'Graphic Novel / Comics',
    categoryId: 'comics',
    shortDesc: 'Cyberpunk sequential panels rendered in glowing retro-futuristic duotones, tracking the hacker rebel Ken.',
    longDesc: 'A revolutionary masterpiece of visual storytelling. Kenji combines classical manga action with industrial cyberpunk layout philosophy. The story profiles an underground group of netrunners decoding ancient analog scrolls which contain coordinates of the natural forests remaining on Earth.',
    pages: 192,
    rating: 4.9,
    year: '2025',
    coverGradient: 'linear-gradient(135deg, #be185d 0%, #831843 100%)',
    published: 'Tokyopop Comics',
    coverImage: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?q=80&w=600&auto=format&fit=crop',
  },
  // Novels
  {
    id: 'nov-1',
    title: 'The Glass Horizon',
    author: 'Isabella Vance',
    genre: 'Historical Novel',
    categoryId: 'novels',
    shortDesc: 'A sweeping narrative tracking three generations of glassblowers in 18th-century Venice.',
    longDesc: 'Set against the shimmering, damp backdrops of historical Murano, Isabella Vance uncovers the secrecy of early glassblowing clans. A romantic and tension-filled exploration of political espionage, illegal colors, and the heartbreaks of those who spun burning sand into fluid art.',
    pages: 520,
    rating: 4.8,
    year: '2024',
    coverGradient: 'linear-gradient(135deg, #b91c1c 0%, #7f1d1d 100%)',
    published: 'Venetian Classics',
    coverImage: 'https://images.unsplash.com/photo-1576016770956-debb63d90029?q=80&w=600&auto=format&fit=crop',
  },
  // Poetry
  {
    id: 'poe-1',
    title: 'Soliloquy of a Leaf',
    author: 'Aria Meadows',
    genre: 'Modern Poetry',
    categoryId: 'poetry',
    shortDesc: 'A delicate collection of haikus, prose, and typographic poems honoring organic cycles and silence.',
    longDesc: ' meadows captures quiet mornings, slow-changing seasons, and the quiet spaces between words. Critics describe this anthology as an essential meditative ritual for slow reading, emphasizing how typography on the page becomes an elegant, visual visual poem by itself.',
    pages: 128,
    rating: 4.9,
    year: '2026',
    coverGradient: 'linear-gradient(135deg, #047857 0%, #064e3b 100%)',
    published: 'Sage Leaf Press',
    coverImage: 'https://images.unsplash.com/photo-1502082553048-f009c37129b9?q=80&w=600&auto=format&fit=crop',
  },
  // Self-Help
  {
    id: 'sh-1',
    title: 'The Kinetic Mindset',
    author: 'Julian Cole',
    genre: 'Personal Mastery',
    categoryId: 'self-help',
    shortDesc: 'Break cycle paralysis by moving physical bodies, adopting modular routines, and owning momentum.',
    longDesc: 'Julian Cole completely debunks long-held myths about raw motivation and willpower. He presents a blueprint centered on "kinetic action states", detailing how localized environments, physical habits, and structured micro-commitments can rewrite neurochemical responses to procrastination.',
    pages: 310,
    rating: 4.6,
    year: '2025',
    coverGradient: 'linear-gradient(135deg, #c2410c 0%, #7c2d12 100%)',
    published: 'Synergy Core',
    coverImage: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?q=80&w=600&auto=format&fit=crop',
  },
  // C++ Systems & High-Performance Design
  {
    id: 'cpp-1',
    title: 'The Titian Compilation',
    author: 'Bjarne S. Sterling',
    genre: 'Systems Architecture',
    categoryId: 'cpp-programming',
    shortDesc: 'A masterpiece detailing compile-time template metaprogramming, memory allocation, and zero-overhead performance.',
    longDesc: 'Combining the pristine, high-performance metal blocks of systems engineering with the luxurious artistic depth of Titian color theories. This text guides senior architects through memory placement new, raw allocation handles, cache alignment bounds, and concurrency primitives designed to scale safely on ultra-low latency hardware.',
    pages: 684,
    rating: 5.0,
    year: '2026',
    coverGradient: 'linear-gradient(135deg, #d32f2f 0%, #3e1b7a 100%)', // Titian Red & Violet
    published: 'Titian Tech Press',
    coverImage: 'https://images.unsplash.com/photo-1515879218367-8466d910aaa4?q=80&w=600&auto=format&fit=crop',
  },
  {
    id: 'cpp-2',
    title: 'Violet Threads of Concurrency',
    author: 'Mira K. Thorne',
    genre: 'Concurrency & Performance',
    categoryId: 'cpp-programming',
    shortDesc: 'A modern C++20/C++23 manual tackling lock-free Ring Buffers, CPU thread affinity, and vector pipeline loops.',
    longDesc: 'Mira K. Thorne provides a pristine guide on how concurrency works in modern C++ systems. Learn how to eliminate race conditions, unlock lock-free atomic buffers, and paint your hardware in deep violet light. Features complete code patterns, real memory barrier diagrams, and compilation benchmarks.',
    pages: 412,
    rating: 4.9,
    year: '2026',
    coverGradient: 'linear-gradient(135deg, #3e1b7a 0%, #d32f2f 100%)', // Violet & Titian Red
    published: 'Circuit Publishing',
    coverImage: 'https://images.unsplash.com/photo-1607799279861-4dd421887fb3?q=80&w=600&auto=format&fit=crop',
  },
];

export const authors: Author[] = [
  {
    id: 'aut-1',
    name: 'Elena Rostova',
    genre: 'Cosmic Fiction',
    shortBio: 'Acclaimed fantasy novelist crafting dense stellar lore and architectural worlds.',
    longBio: 'Elena Rostova is a world-class world-builder whose novels regularly top global charts. With a background in astrophysics and ancient history, her narratives intertwine real-world scientific laws with magical realism, spawning a massive community of stargazing fans.',
    avatar: 'ER',
    achievement: 'Hugo Award Winner 2025',
    featuredBook: 'The Starlight Epoch',
    image: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?q=80&w=400&auto=format&fit=crop',
  },
  {
    id: 'aut-2',
    name: 'Dr. Arthur Sterling',
    genre: 'Design & Philosophy',
    shortBio: 'Cultural anthropologist examining spaces of silence and urban design.',
    longBio: 'Dr. Arthur Sterling has lectured in over forty countries regarding human architecture. His primary work is investigating sensory overload in megacities and proposing design rules to keep human communities sane, quiet, and grounded in nature.',
    avatar: 'AS',
    achievement: 'Pulitzer Prize Nominee',
    featuredBook: 'Architectures of Quiet',
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=400&auto=format&fit=crop',
  },
  {
    id: 'aut-3',
    name: 'Professor Lucas Crane',
    genre: 'Web UI & Computer Science',
    shortBio: 'Pioneering frontend developer, designing frameworks of motion design.',
    longBio: 'Lucas Crane is a legendary Web designer and active tech evangelist. In his academic roles, he researches kinetic UI transitions and assists software companies in making digital workflows intuitive, tactile, and highly responsive.',
    avatar: 'LC',
    achievement: 'Developer of the Year 2025',
    featuredBook: 'Design Systems in Motion',
    image: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?q=80&w=400&auto=format&fit=crop',
  },
  {
    id: 'aut-4',
    name: 'Aria Meadows',
    genre: 'Modern Poetry',
    shortBio: 'Poetess and digital typographer crafting delicate verses on organic cycles.',
    longBio: 'Aria Meadows combines classic prose structure with modern typographic layouts. Her viral poetry has been projected on massive architecture projects in Tokyo, London, and New York, bridging ancient haiku styles with electronic displays.',
    avatar: 'AM',
    achievement: 'National Book Award 2024',
    featuredBook: 'Soliloquy of a Leaf',
    image: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=400&auto=format&fit=crop',
  },
];

export const sessions: EventSession[] = [
  {
    id: 'sess-1',
    time: '10:00 AM - 11:30 AM',
    title: 'The Great Convergence: Opening & Keynote',
    speaker: 'Elena Rostova & Guest Panelists',
    role: 'Cosmic Fiction Author',
    location: 'Main Pavilion: The Nebula Stage',
    desc: 'Unveiling Bookverse 2026. A panel discussing why space adventures and human lore remain critical as we look into the next decade of digital evolution.',
  },
  {
    id: 'sess-2',
    time: '12:00 PM - 01:30 PM',
    title: 'Crafting Silence: Architecture and Mind',
    speaker: 'Dr. Arthur Sterling',
    role: 'Author of "Architectures of Quiet"',
    location: 'Atrium 2: The Zen Corner',
    desc: 'An exploration of spatial meditation, physical architecture, and a live practice on finding focus within towering modern concrete metropolitan structures.',
  },
  {
    id: 'sess-3',
    time: '02:00 PM - 03:30 PM',
    title: 'Tactile Pixels: Front-End Motion Design Masterclass',
    speaker: 'Professor Lucas Crane',
    role: 'Creative Engineer',
    location: 'Lab A: Interactive Computing Hub',
    desc: 'A physical code coding review showcasing CSS 3D capabilities, spring physics mechanics, and spatial web animations that adapt smoothly across all interfaces.',
  },
  {
    id: 'sess-4',
    time: '04:00 PM - 05:30 PM',
    title: 'Ink and Stars: Typographic Poetry Recital',
    speaker: 'Aria Meadows',
    role: 'Poet & Visual Artist',
    location: 'The Garden Stage: Whisper Fields',
    desc: 'A live audio and light layout reading of Meadows\' anthology. Followed by a Q&A on merging the physical texture of print with transient projector canvas installations.',
  },
  {
    id: 'sess-5',
    time: '06:00 PM - 08:30 PM',
    title: 'Bookverse Cosmic Soirée & Author Signing Guild',
    speaker: 'All Showcase Authors',
    role: 'Exclusive Bookverse Authors',
    location: 'Grand Ballroom: The Infinite Library',
    desc: 'The grand finale. Collect signed exclusive physical versions of showcased volumes, mingle with fellow book lovers under a projected aurora sky, and toast to the shared universe of stories.',
  },
];
